### ISSUE TITLE
Request: HiBitUninstaller-Portable

### ISSUE THREAD

**Issue by Meng5in** [batkiz/backit#3]
PackageName: HiBitUninstaller-Portable
PackageType: Portable
Homepage: http://www.hibitsoft.ir/Uninstaller.html
Version: 2.6.15
URL: http://www.hibitsoft.ir/HiBitUninstaller/HiBitUninstaller-Portable-2.6.15.zip

自从用了这个软件，我就把Geekuninstaller、wise care 365、Advanced Systemcare全卸载了！

JSON真的好困难啊！不然我就自己提PR了……
麻烦了！谢谢！

**Comment by batkiz** [comment]
前两天在外边没看 GitHub，我晚点看看这个软件

**Comment by Meng5in** [comment]
> 前两天在外边没看 GitHub，我晚点看看这个软件

麻烦啦！

**Comment by Meng5in** [comment]
然后我自己试着写了一个manifest，不知道有多少错误🤣 
#4

**Comment by Meng5in** [comment]
我是不是合并错branch了😢
