### ISSUE TITLE
RevokeMsgPatcher@1.2: Hash check failed

### ISSUE THREAD

**Issue by diklios5768** [batkiz/backit#9]
Hash check failed!
App:         backit/RevokeMsgPatcher
URL:         https://github.com/huiyadanli/RevokeMsgPatcher/releases/download/1.2/RevokeMsgPatcher.v1.2.zip
First bytes: 80 75 3 4 10 0 0 0
Expected:    fccede94dc58ee88b1e9f64ed7875b765b4c990b4a7e5cfd0250949edaef1a63
Actual:      5537380857e0678f8aa8b6cd2dcbde26f718988049ffea2eefc3e2d648af1b48

**Comment by batkiz** [comment]
fixed.
